### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by NickiHell** [ags131/docker-screeps-server#15]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node-gyp]
 2: 0x11e7fec [node-gyp]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node-gyp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node-gyp]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node-gyp]
 6: 0xdee3b3 [node-gyp]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node-gyp]
 8: 0x2695fd2042fd
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! isolated-vm@1.7.2 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the isolated-vm@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-02T03_07_49_241Z-debug.log
Install for screeps@latest failed with code 134

2018-10-02T03_07_49_241Z-debug.log:
```
14576 silly install isolated-vm@1.7.2
14577 info lifecycle isolated-vm@1.7.2~install: isolated-vm@1.7.2
14578 verbose lifecycle isolated-vm@1.7.2~install: unsafe-perm in lifecycle false
14579 verbose lifecycle isolated-vm@1.7.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.npm/_npx/43/lib/node_modules/screeps/node_modules/isolated-vm/node_modules/.bin:/root/.npm/_npx/43/lib/node_modules/screeps/node_modules/.bin:/root/.npm/_npx/43/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
14580 verbose lifecycle isolated-vm@1.7.2~install: CWD: /root/.npm/_npx/43/lib/node_modules/screeps/node_modules/isolated-vm
14581 silly lifecycle isolated-vm@1.7.2~install: Args: [ '-c', 'node-gyp rebuild --release -j 4' ]
14582 silly lifecycle isolated-vm@1.7.2~install: Returned: code: 134  signal: null
14583 info lifecycle isolated-vm@1.7.2~install: Failed to exec install script
14584 verbose unlock done using /root/.npm/_locks/staging-d4c61f5c68559b1a.lock for /root/.npm/_npx/43/lib/node_modules/.staging
14585 warn ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
14586 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/screeps/node_modules/fsevents):
14587 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
14588 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
14588 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
14588 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
14588 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
14589 verbose stack Error: isolated-vm@1.7.2 install: `node-gyp rebuild --release -j 4`
14589 verbose stack Exit status 134
14589 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
14589 verbose stack     at emitTwo (events.js:126:13)
14589 verbose stack     at EventEmitter.emit (events.js:214:7)
14589 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14589 verbose stack     at emitTwo (events.js:126:13)
14589 verbose stack     at ChildProcess.emit (events.js:214:7)
14589 verbose stack     at maybeClose (internal/child_process.js:925:16)
14589 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14590 verbose pkgid isolated-vm@1.7.2
14591 verbose cwd /screeps
14592 verbose Linux 4.15.0-34-generic
14593 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "screeps@latest" "--global" "--prefix" "/root/.npm/_npx/43" "--loglevel" "error" "--json"
14594 verbose node v8.11.1
14595 verbose npm  v5.6.0
14596 error code ELIFECYCLE
14597 error errno 134
14598 error isolated-vm@1.7.2 install: `node-gyp rebuild --release -j 4`
14598 error Exit status 134
14599 error Failed at the isolated-vm@1.7.2 install script.
14599 error This is probably not a problem with npm. There is likely additional logging output above.
14600 verbose exit [ 134, true ]
```

Happens when try to: docker exec -it screeps-server npx screeps cli

**Comment by AlinaNova21** [comment]
The out of memory error is common on lower memory systems <= 1GB RAM, it ends up using quite a bit to build ivm. It should be using the already existing version though, check and make sure the `screeps` dependency is saved to package.json, that will help keep npx from trying to reinstall it on every run.
